//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ReportMaker01.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDI_ICON                        101
#define IDR_MAINFRAME                   128
#define IDR_ReportMaker01TYPE           130
#define IDD_FIRSTELEVEN_DLG             310
#define IDD_EVENT_DLG                   311
#define IDD_PLAYEREDIT_DLG              312
#define IDD_EVENTEDIT                   313
#define IDD_EVENTEDIT_DLG               313
#define IDD_PLAYEREDIT_DLG1             314
#define IDB_DOWN                        316
#define IDB_END                         317
#define IDB_GOAL                        318
#define IDB_HT                          319
#define IDB_OWNGOAL                     320
#define IDB_PENALTY                     321
#define IDB_PENALTYMISS                 322
#define IDB_RED                         323
#define IDB_START                       324
#define IDB_UP                          325
#define IDB_YELLOW                      326
#define IDB_TWOYELLOW                   327
#define IDB_EXPLANATION                 328
#define IDD_GAMENAME                    330
#define IDD_PENALTY                     331
#define IDD_PLAYER_DLG                  333
#define IDD_FORMAT                      335
#define IDD_CHECK_DLG                   338
#define EVENT_GOAL                      900
#define EVENT_OWNGOAL                   901
#define EVENT_SUBSTITUTION              902
#define EVENT_YELLOW                    903
#define EVENT_RED                       904
#define EVENT_TWOYELLOW                 905
#define EVENT_PENALTY                   906
#define EVENT_PENALTYMISS               907
#define PLAYER_XIAOYOU                  908
#define PLAYER_ZUTE                     909
#define PLAYER_JIAOGONG                 910
#define PLAYER_CAPTAIN                  911
#define PLAYER_GOALKEEPER               912
#define PLAYER_NULL                     913
#define IDC_HOME_PLAYER_LIST            1000
#define IDC_AWAY_PLAYER_LIST            1001
#define IDC_HOMENAME_EDIT               1003
#define IDC_HOMENAMEOK_BOTTON           1004
#define IDC_HOME_PLAYERNUM_EDIT         1005
#define IDC_AWAYNAME_EDIT               1006
#define IDC_HOME_PLAYERNAME_EDIT        1007
#define IDC_HOME_PLAYEREXTRA_COMBO      1008
#define IDC_HOME_PLAYEROK_BUTTON        1009
#define IDC_EVENT_PLAYEROUTEXTRA_COMBO  1009
#define IDC_HOME_PLAYERDELETE_BOTTON    1010
#define IDC_EVENT_PLAYERINEXTRA_COMBO   1010
#define IDC_AWAYNAMEOK_BOTTON           1011
#define IDC_HOME_PLAYERNUM_CHECK        1012
#define IDC_AWAY_PLAYERNUM_EDIT         1013
#define IDC_EVENT_LIST                  1013
#define IDC_AWAY_PLAYERNAME_EDIT        1014
#define IDC_AWAY_PLAYEREXTRA_COMBO      1015
#define IDC_AWAY_PLAYEROK_BUTTON        1016
#define IDC_EVENT_TIME_EDIT             1016
#define IDC_AWAY_PLAYERDELETE_BOTTON    1017
#define IDC_AWAY_PLAYERNUM_CHECK        1018
#define IDC_EVENT_TYPE_COMBO            1018
#define IDC_EVENT_PLAYERNUM_COMBO       1019
#define IDC_EVENT_PLAYERNAME_EDIT       1020
#define IDC_PLAYEROUTNUM_COMBO          1021
#define IDC_PLAYERINNUM_COMBO           1022
#define IDC_PLAYEROUTNAME_EDIT          1023
#define IDC_PLAYERINNUM_EDIT            1024
#define IDC_EVENTOK                     1025
#define IDC_EVENT_DELETE_BOTTON         1027
#define IDC_EVENT_EDIT_BOTTON           1028
#define IDC_HOME_PLAYEREDIT_BOTTON      1029
#define IDC_AWAY_PLAYEREDIT_BOTTON      1031
#define IDC_PLAYERNUM_EDIT              1032
#define IDC_PLAYERNUM_CHECK             1033
#define IDC_PLAYERNAME_EDIT             1034
#define IDC_PLAYEROUTNUM_CHECK          1034
#define IDC_PLAYEREXTRA_COMBO           1035
#define IDC_PLAYERINNUM_CHECK           1035
#define IDC_HOMEREFRESH_BOTTON          1036
#define IDC_AWAYREFRESH_BOTTON          1037
#define IDC_HOMEPLAYERUP_BOTTON         1038
#define IDC_HOMRPLAYERDOWN_BOTTON       1039
#define IDC_AWAYPLAYERUP_BOTTON         1040
#define IDC_EVENT_STOPPAGETIME_EDIT     1040
#define IDC_AWAYPLAYERDOWN_BOTTON       1041
#define IDC_PLAYERINNAME_EDIT           1041
#define IDC_PLAYERNAME_COMBO            1042
#define IDC_PLAYEROUTNAME_COMBO         1043
#define IDC_OK                          1044
#define IDC_EVENTHOME_RADIO             1045
#define IDC_EVENTAWAY_RADIO             1046
#define IDC_NAMEPLAYEROUT_STATIC        1047
#define IDC_NAMEPLAYERIN_STATIC         1048
#define IDC_PLAYEROUT_STATIC            1049
#define IDC_PLAYERIN_STATIC             1050
#define IDC_PLAYERNAME_STATIC           1051
#define IDC_PLAYEREXTRA_STATIC          1053
#define IDC_PLAYEROUTEXTRA_STATIC       1054
#define IDC_PLAYERINEXTRA_STATIC        1055
#define IDC_EVENT_PLAYEREXTRA_COMBO     1056
#define IDC_EVENTREFRESH_BOTTON         1058
#define IDC_CANCEL                      1060
#define IDC_EVENTUP_BUTTON              1061
#define IDC_EVENTDOWN_BUTTON            1062
#define IDC_HOMENUM_STATIC              1063
#define IDC_AWAYNUM_STATIC              1064
#define IDC_GAMENAME_EDIT               1064
#define IDC_PENALTY_CHECK               1065
#define IDC_HOME_STATIC                 1066
#define IDC_HOMENUM_COMBO               1067
#define IDC_HOMENAME_COMBO              1068
#define IDC_HOMEGOAL_RADIO              1069
#define IDC_HOMEMISS_RADIO              1070
#define IDC_HOME_LIST                   1071
#define IDC_HOMEDEL_BUTTON              1072
#define IDC_HOMEUP_BUTTON               1073
#define IDC_HOMEDOWN_BUTTON             1074
#define IDC_AWAY_STATIC                 1075
#define IDC_AWAYNUM_COMBO               1076
#define IDC_AWAYNAME_COMBO              1077
#define IDC_AWAYGOAL_RADIO              1078
#define IDC_AWAYMISS_RADIO              1079
#define IDC_AWAY_LIST                   1080
#define IDC_AWAYDEL_BUTTON              1081
#define IDC_AWAYUP_BUTTON               1082
#define IDC_AWAYDOWN_BUTTON             1083
#define IDC_HOMEADD_BUTTON              1084
#define IDC_AWAYADD_BUTTON              1085
#define IDC_TIME_EDIT                   1086
#define IDC_AWAYLIST                    1090
#define IDC_HOMELIST                    1091
#define IDC_HOMEDEL_BN                  1093
#define IDC_HOMEREFRESH_BN              1096
#define IDC_SLIDERRED                   1097
#define IDC_SLIDERGREEN                 1098
#define IDC_SLIDERBLUE                  1099
#define IDC_STATICRED                   1100
#define IDC_STATICGREEN                 1101
#define IDC_STATICBLUE                  1102
#define IDC_COMBOTITLE                  1103
#define IDC_COMBONAME                   1104
#define IDC_COMBOTEXT                   1106
#define IDC_BUTTONDEFAULT               1107
#define IDC_AWAYDEL_BN                  1108
#define IDC_COMBONAMEFIRST              1108
#define IDC_AWAYREFRESH_BN              1111
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_FIRSTELEVEN                  32773
#define ID_EVENT                        32774
#define ID_32775                        32775
#define ID_DRAW                         32776
#define ID_32785                        32785
#define ID_SAVEPIC                      32786
#define ID_32789                        32789
#define ID_GAMENAME                     32791
#define ID_32793                        32793
#define ID_PENALTY                      32794
#define ID_32795                        32795
#define ID_32801                        32801
#define ID_FORMAT                       32802
#define ID_32803                        32803
#define ID_VIDEO                        32804
#define ID_PLAYER                       32805
#define ID_32806                        32806
#define ID_CHECK                        32807
#define ID_Menu                         32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        339
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
